articles/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path('',views.article_view,name='blog_list'),
    path('blog_detail/',views.article_detail,name='blog_detail'),
]

authentication/urls.py
from django.urls import path
from .import views

app_name='contacts'

urlpatterns=[
    path('',views.contacts,name='contacts'),
]

designers/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index_view,name='index'),
    path('about/',views.about_view,name='about'),
    path('services/',include('services.urls',namespace='services')),
    path('ecomerce/',include('ecomerce.urls',namespace='ecomerce')),
    path('blog/',include('articles.urls',namespace='blog')),
    path('users/',include('authentication.urls',namespace='authentication')),
]

ecomerce/urls.py
from django.urls import path
from . import views

app_name='ecomerce'

urlpatterns=[
    path('',views.ecomerce_view,name='index'),
    path('cart/',views.cart_view,name='cart'),
    path('checkout/',views.checkout_view,name='checkout'),
]

services/urls.py
from django.urls import path
from . import views

app_name='services'

urlpatterns=[
    path('',views.service_view,name='index'),
    path('service_detail/',views.service_detail,name='service_detail'),
]

articles/models.py
from django.db import models

# Create your models here.

authentication/models.py
from django.db import models

# Create your models here.

ecomerce/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render

# Create your views here.
def article_view(request):
    return render(request,'blog.html')

def article_detail(request):
    return render(request,'blog_detail.html')

authentication/views.py
from django.shortcuts import render

# Create your views here.

def contacts(request):
    return render(request,'contact.html')

designers/views.py
from django.shortcuts import render

def index_view(request):
    return render(request,'index.html')

def about_view(request):
    return render(request,'about.html')

ecomerce/views.py
from django.shortcuts import render

# Create your views here.
def ecomerce_view(request):
    return render(request,'shop.html')

def cart_view(request):
    return render(request,'cart.html')

def checkout_view(request):
    return render(request,'cart.html')

projects/views.py
from django.shortcuts import render

# Create your views here.

services/views.py
from django.shortcuts import render

# Create your views here.
def service_view(request):
    return render(request,'services.html')

def service_detail(request):
    return render(request,'service_detail.html')

templates/includes/footer.html
<div class="footer-widgets__container">
<div class="footer-widgets__col">
<aside id="media_image-3" class="widget widget--footer widget_media_image">
<img width="246" height="62" src="https://demo.brothersthemes.com/phone-repair/wp-content/uploads/sites/3/2016/12/logo.png" class="image wp-image-111  attachment-full size-full" alt="" style="max-width: 100%; height: auto;" />
</aside>
<aside id="text-6" class="widget widget--footer widget_text">
<div class="textwidget">
<p>In nulla nibh, malesuada sit amet purus id, mollis auctor ex. In sit amet venenatis eros. Curabitur sed convallis mauris. Nam eget volutpat 
purus, ut egestas nulla. Nunc scelerisque eros vitae lacus dictum dictum. Donec luctus ligula lectus, eu auctor sem sollicitudin sit amet.</p>
</div>
</aside>
</div>
<div class="footer-widgets__col">
<aside id="nav_menu-2" class="widget widget--footer widget_nav_menu">
<h3 class="widget__title">Company</h3>
<div class="menu-menu-1-container">
<ul id="menu-menu-2" class="menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-1753">
<a href="https://demo.brothersthemes.com/phone-repair/">Home</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-1757">
<a href="https://demo.brothersthemes.com/phone-repair/">Home 1</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1754">
<a href="https://demo.brothersthemes.com/phone-repair/home-2/">Home 2</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-1505 current_page_item menu-item-1755">
<a href="https://demo.brothersthemes.com/phone-repair/home-3/" aria-current="page">Home 3</a></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1756">
<a href="https://demo.brothersthemes.com/phone-repair/home-4/">Home 4</a>
</li></ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-163">
<a href="https://demo.brothersthemes.com/phone-repair/about-us/">About us</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-166">
<a href="https://demo.brothersthemes.com/phone-repair/services/">Services</a><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-service menu-item-1496">
<a href="https://demo.brothersthemes.com/phone-repair/service/water-damage/">Single Service 1</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-service menu-item-1497">
<a href="https://demo.brothersthemes.com/phone-repair/service/wifi-problems/">Single Service 2</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1458">
<a href="https://demo.brothersthemes.com/phone-repair/services/">Services 1</a>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1457">
<a href="https://demo.brothersthemes.com/phone-repair/services-2/">Services 2</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1456">
<a href="https://demo.brothersthemes.com/phone-repair/services-3/">Services 3</a></li></ul></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1430">
<a href="https://demo.brothersthemes.com/phone-repair/shop/">Shop</a><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type_archive menu-item-object-product menu-item-1434">
<a href="https://demo.brothersthemes.com/phone-repair/shop/">All Products</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1431">
<a href="https://demo.brothersthemes.com/phone-repair/cart/">Cart</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1432">
<a href="https://demo.brothersthemes.com/phone-repair/checkout/">Checkout</a></li>
</ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-169">
<a href="https://demo.brothersthemes.com/phone-repair/blog/">Blog</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1462">
<a href="https://demo.brothersthemes.com/phone-repair/contacts/">Contacts</a>
<ul class="sub-menu"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1465">
<a href="https://demo.brothersthemes.com/phone-repair/contacts/">Contacts 1</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1464">
<a href="https://demo.brothersthemes.com/phone-repair/contacts-2/">Contacts 2</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1463">
<a href="https://demo.brothersthemes.com/phone-repair/contacts-3/">Contacts 3</a></li>
</ul></li></ul></div></aside></div><div class="footer-widgets__col">
<aside id="text-4" class="widget widget--footer widget_text"><h3 class="widget__title">Contacts</h3>
<div class="textwidget"><p><span class="fa fa-phone" style="padding-right:10px;color:#F7A5B1">
</span> 1-888-777-55555<br /> <span class="fa fa-map-marker" style="padding-right:13px;color:#F7A5B1">
</span> 131 Lonsdale St, Melbourne VIC 3000, Australia<br /> 
<span class="fa fa-envelope" style="padding-right:10px;color:#F7A5B1"></span> 
<a href="mailto:phone-repair@example.com">phone-repair@example.com</a></p></div></aside>
<aside id="text-5" class="widget widget--footer widget_text"><h3 class="widget__title">Follow us</h3>
<div class="textwidget"><a href="#"> <span class="fa fa-2x fa-facebook-square" style="padding-right:10px;color:#fff">
</span></a> <a href="#"> <span class="fa fa-2x fa-google-plus-square" style="padding-right:10px;color:#fff"></span>
</a> <a href="#"> <span class="fa fa-2x fa-flickr" style="padding-right:10px;color:#fff"></span></a> <a href="#">
<span class="fa fa-2x fa-tumblr-square" style="padding-right:10px;color:#fff"></span></a></div></aside></div>
</div></div><div class="footer-copyright"><div class="footer-copyright__container"> Phone Repair © 2020</div></div>
					
					

templates/includes/header.html
<div class="header__top">
    <div class="topbar-wrapper">
    <div class="header__topbar topbar">
    <div class="topbar__left">
    <a href="#" class="social-link"> 
    <span class="fa fa-facebook">
    </span>
    </a>
     <a href="#" class="social-link"> 
     <span class="fa fa-twitter">
     </span>
     </a> 
     <a href="#" class="social-link"> 
     <span class="fa fa-instagram"></span>
     </a>
     </div>
     <div class="topbar__center">
     Opening Time:&nbsp; Mon&#8209;Fri&nbsp;&nbsp;08:00&#8209;18:00&nbsp;&nbsp; Sat&#8209;Sun&nbsp;10:00&#8209;17:00
     </div>
     <div class="topbar__right">
     Call now:&nbsp;&nbsp;1-888-777-55555
     </div>
     </div>
     </div>
     <div class="navigation-bar js-navigation-bar">
     <div class="navigation-bar__logo-and-toggle-wrap">
     <div class="navigation-bar__logo header-logo"> 
     <a href="https://demo.brothersthemes.com/phone-repair/"> 
     <img class="header-logo__img" src="https://demo.brothersthemes.com/phone-repair/wp-content/uploads/sites/3/2016/12/logo.png" alt="Phone Repair" /> 
     </a>
     </div> 
     <button class="navigation-bar__mobile-menu-toggle js-navigation-bar__mobile-menu-toggle burger-button" type="button"> 
     <span class="screen-reader-text">
     Toggle navigation menu
     </span>
      <span class="burger-button__bar">
      </span> 
      <span class="burger-button__bar">
      </span> 
      <span class="burger-button__bar">
      </span> 
      </button>
      </div>
      <ul class="navigation-bar__menu js-navigation-bar__menu is-closed primary-menu js-primary-menu">
      <li id="menu-item-1753" class="primary-menu__item primary-menu__item--ancestor primary-menu__item--parent primary-menu__item--has-sub-menu js-primary-menu__item--has-sub-menu menu-item-1753">
      <a href="/">Home</a>
      </li><li id="menu-item-163" class="primary-menu__item menu-item-163"><a href="{% url 'about' %}">About us</a></li><li id="menu-item-166" class="primary-menu__item primary-menu__item--has-sub-menu js-primary-menu__item--has-sub-menu menu-item-166"><a href="{% url 'services:index' %}">Services</a>
      </li>
      <li id="menu-item-1430" class="primary-menu__item primary-menu__item--has-sub-menu js-primary-menu__item--has-sub-menu menu-item-1430"><a href="https://demo.brothersthemes.com/phone-repair/shop/">Shop</a><ul class="primary-menu__sub-menu primary-menu__sub-menu--level-1 js-primary-menu__sub-menu"><li id="menu-item-1434" class="primary-menu__sub-menu-item menu-item-1434"><a href="{% url 'ecomerce:index' %}">All Products</a></li><li id="menu-item-1431" class="primary-menu__sub-menu-item menu-item-1431"><a href="{% url 'ecomerce:cart' %}">Cart</a></li><li id="menu-item-1432" class="primary-menu__sub-menu-item menu-item-1432"><a href="{% url 'ecomerce:checkout' %}">Checkout</a></li></ul></li><li id="menu-item-169" class="primary-menu__item menu-item-169"><a href="{% url 'blog:blog_list' %}">Blog</a></li>
      <li id="menu-item-1462" class="primary-menu__item primary-menu__item--has-sub-menu js-primary-menu__item--has-sub-menu menu-item-1462"><a href="{% url 'authentication:contacts' %}">Contacts</a>
      </li>
      </ul></div>
      </div>